# Generated by Django 5.0.1 on 2024-02-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_car', models.CharField(max_length=50)),
                ('fecha_creacion_car', models.DateField()),
                ('telefono_car', models.CharField(max_length=10)),
            ],
        ),
    ]
