# Generated by Django 5.0.1 on 2024-09-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0003_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fk_id_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Educacion.carrera'),
        ),
    ]
