# Generated by Django 5.0.1 on 2024-09-10 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0004_alter_curso_fk_id_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mat', models.CharField(max_length=50)),
                ('creditos_mat', models.IntegerField()),
                ('silabo_mat', models.FileField(null=True, upload_to='silabos')),
                ('fk_id_cur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Educacion.curso')),
            ],
        ),
    ]
